### ISSUE TITLE
Unit tests fail on Frontier after recent module updates

### ISSUE THREAD

**Issue by philipwjones** [E3SM-Project/Omega#104]
Recent updates of modules on Frontier are preventing successful builds, so the E3SM config_machine must be updated.

As a workaround, the default compiler configurations appear to work for the crayclang (CPU) and crayomegagpu (GPU) options:
   PrgEnv-amd/8.5.0
   PrgEnv-cray-amd/8.5.0
   PrgEnv-cray/8.5.0
   PrgEnv-gnu-amd/8.5.0
   PrgEnv-gnu/8.5.0
   amd/5.7.1
   craype/2.7.31
   cce/17.0.0
   cpe/23.12
   gcc/12.2.0
   rocm/5.7.1

   cray-netcdf-hdf5parallel/4.9.0.9
   cray-hdf5-parallel/1.12.2.9
   cray-parallel-netcdf/1.12.3.9

I don't know if these options will work for the E3SM builds, so the eventual solution may be different.

**Comment by philipwjones** [comment]
Workaround posted here as promised on today's omega call @sbrus89 @xylar

**Comment by xylar** [comment]
Thanks @philipwjones!

**Comment by philipwjones** [comment]
I recently inadvertantly built omega with the old modules to test a PR and they appear to all be working again - not sure if OLCF reinstalled old mods for back-compatibility?  We should still update to more recent versions, but workaround may no longer be necessary.

**Comment by grnydawn** [comment]
@philipwjones, thanks for the info. I was also able to successfully build and run Omega without updating the modules. In any case, I will keep working on updating the e3sm machine config and then update the Omega config.

**Comment by grnydawn** [comment]
@sbrus89 , I could not reproduce it because I could not get allocation on Frontier today. If you can share the location of the Omega build directory with me, I will look into it.

**Comment by mwarusz** [comment]
@sbrus89 
I got the same error on gpu when I tried testing #105 on Frontier yesterday. I was using `crayclanggpu`. Cpu build with `gnu` worked fine.

**Comment by grnydawn** [comment]
@sbrus89, @mwarusz, try to use "crayomegagpu" instead of "crayclanggpu." Until Omega is fully compatible with E3SM configurations, we want to use Omega-specific configurations including "crayomegagpu," "gnuomegagpu," and "amdomegagpu."

**Comment by sbrus89** [comment]
Thanks @philipwjones and @grnydawn!

**Comment by grnydawn** [comment]
This issue is resolved by https://github.com/E3SM-Project/Omega/pull/149. Closing the issue.
