### ISSUE TITLE
Copy of `Default.yml` in build directory

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/Omega#126]
Polaris needs to have a copy of https://github.com/E3SM-Project/Omega/blob/develop/components/omega/configs/Default.yml placed somewhere in the build directory.  Otherwise, Polaris users will need to point both to the build directory (to get `omega.exe`) and the source directory (to get `Default.yml`), which is too inconvenient to be worth considering in my view.

**Comment by xylar** [comment]
@brian-oneill or @grnydawn, is this something that one of you could take on?  I don't care where the file ends up but presumably it would make sense for it to be in `config/Default.yml` within the build directory.  Presumably, this will eventually be the place where we construct the defaults via parsing the C++ headers instead.

**Comment by grnydawn** [comment]
I think I can take this on because it is trivial to copy Default.yml from the source directory to the build directory during CMake configuration, if that is all that is required without further modification of the YAML file. In fact, I would like to add some tracer parameters to the YAML file so that they can be used during the tracer ctest.

**Comment by xylar** [comment]
@grnydawn, that would be great!  Can you also copy `UnitTest.yml` into the `test` directory.  That's currently listed as a manual step in the docs:
https://github.com/E3SM-Project/Omega/blob/develop/components/omega/doc/devGuide/QuickStart.md?plain=1#L152-L154

**Comment by grnydawn** [comment]
@xylar, sure, I can. So, what needs to be done is copying both Default.yml and UnitTest.yml to the test directory and renaming UnitTest.yml to omega.yml?

**Comment by xylar** [comment]
I believe `Default.yml` should get copied into a directory within the build directory, e.g. `config`.  It would be fine to also copy `UnitTest.yml` there but I'm not sure that would end up being useful.

Then, `UniteTest.yml` would get copied to the `test` directory within the build directory and renamed to `omega.yml`.  Does that make sense?

**Comment by xylar** [comment]
The reason for for first part with `Default.yml` is that Polaris only knows where the build directory is, not the source directory.  So I just want some consistent path to `Default.yml` within the build directory.

**Comment by grnydawn** [comment]
@xylar , Ok. copying Default.yml to "config" subdirectory of Omega build directory. One thing that I am confused is that Mark uses Default.yml for "omega.yml" instead of UnitTests.yml as shown here: https://github.com/E3SM-Project/Omega/pull/123#issuecomment-2353351612 . UnitTest

**Comment by xylar** [comment]
@mark-petersen can comment but I believe they are currently similar enough that it doesn't happen to matter. But in the future I think only `UnitTest.yml` is likely to work for CTests. @mark-petersen, maybe update your workflow accordingly.

**Comment by grnydawn** [comment]
@xylar , @mark-petersen , To support both of Polaris and some Omega unit tests, I think I need to use Default.yml for omega.yml for now. I will follow-up this issue.

**Comment by mark-petersen** [comment]
We just want a single file, `components/omega/configs/Default.yml` that defines the defaults. The unit tests would also read in `Default.yml` and then change flag settings as needed for that test. So I think `UnitTest.yml` is simply not needed and should be removed. 

@brian-oneill do you agree, or does `UnitTest.yml` have a different function?

**Comment by brian-oneill** [comment]
The `UnitTest.yml` was separate to allow for the possibility that unit tests would have distinct configurable options from the `Default.yml`. If we just decide to set any distinct options within the source of a particular unit test, than yeah we could remove it.

**Comment by grnydawn** [comment]
@mark-petersen, @xylar, @brian-oneill, per our discussion here, I plan to remove UnitTest.yml in the upcoming PR. I support changing the options in the unit test source code because the developer of the unit tests can decide to use all, some, or none of the options
