### ISSUE TITLE
IOStreamTest Failures on Chrysalis

### ISSUE THREAD

**Issue by brian-oneill** [E3SM-Project/Omega#150]
On Chrysalis, the IOStreamTest unit test will pass occasionally, but fails about 90% of the time. Haven't noticed an issue on other platforms. Tested with intel build, using Parmetis lib in `/lcrc/soft/climate/polaris/chrysalis/spack/dev_polaris_0_4_0_intel_openmpi/var/spack/environments/dev_polaris_0_4_0_intel_openmpi/.spack-env/view`.

This is the only readable error it spits out:
``testIOStream.exe: /home/ac.boneill/proj_space/myFork/Omega/externals/scorpio/src/clib/spio_io_summary.cpp:64: void cache_file_stats(int, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &, const PIO_Util::IO_Summary_Util::IO_summary_stats &): Assertion `filename.size() > 0' failed.``

**Comment by philipwjones** [comment]
The test attempts to read a restart just after writing the last restart and sometimes the write hasn't completed. I tried to add some extra work and syncs to give it time, but apparently that's not enough. I just tried adding an explicit delay of 10 seconds and that seems to be enough. The unit test ran four times in a row.  I'll push a fix later today. Makes the unit test look artificially long in the stats and swaps the total unfortunately.
