### ISSUE TITLE
Ctests on Perlmutter-GPU with nvidiagpu running much more slowly than on Perlmutter-CPU with nvidia

### ISSUE THREAD

**Issue by altheaden** [E3SM-Project/Omega#165]
@xylar and I noticed that ctests on pm-cpu with nvidia ran at about 90 seconds, but on pm-gpu with nvidiagpu they ran at 1538.76 seconds.

**Comment by xylar** [comment]
This seems qualitatively similar to the slow Intel performance we've seen: https://github.com/E3SM-Project/Omega/issues/119  But this case seems even worse.  25 minutes instead of 1.5 is really quite bad!

**Comment by xylar** [comment]
It could be that Polaris or Omega itself isn't setting some environment variables that are needed or something like that.

**Comment by xylar** [comment]
I ran the tests myself and they didn't take that long.  They're still quite slow but only took 577.79 seconds (about 10 minutes)

**Comment by mwarusz** [comment]
I think part of this issue is startup times of slurm steps and this might be related: https://docs.nersc.gov/jobs/best-practices/#limit-your-queries-to-the-batch-system

**Comment by xylar** [comment]
Closing this because the issue seems to be with slurm on Perlmutter, not Omega.  See #119
