### ISSUE TITLE
Should it be an error if `RestartRead` is not present in `omega.yml`?

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/Omega#175]
I got an error when `RestartRead` was not present in `omega.yml`.  For most Polaris tests, we don't anticipate needing a restart.  It's not a problem to include a `RestartRead` entry in the `IOStreams` but I wanted to make sure that the requirement that it be there is intentional.

**Comment by philipwjones** [comment]
Didn't think about the case where the entry isn't needed and is missing so I guess I need to catch that while still making sure the state is initialized. Are you initializing with the InitialState in these cases or will there be cases where we will initialize a test case with internal analytical data without reading one of those two streams?

**Comment by xylar** [comment]
We always initialize with `InitialState` whenever we wouldn't be using `RestartRead`.  I don't think we plan to initialize from an analytic initial condition in Omega itself.
