### ISSUE TITLE
Wrong loop syntax in IO tests

### ISSUE THREAD

**Issue by mwarusz** [E3SM-Project/Omega#49]
https://github.com/E3SM-Project/Omega/blob/f09a0d5925930d7f9d68ace2b755a40250fc1c13/components/omega/test/base/IOTest.cpp#L119

I think this should be 
```cpp
for (int Cell = 0; Cell < NCellsOwned; ++Cell) {
```
and similarly for other loops in this file

@philipwjones

**Comment by philipwjones** [comment]
Ha! That's weird - not sure where that syntax came from. I'll push a fix today
