### ISSUE TITLE
With `nvidia` on `pm-cpu`, can't build yaml-cpp from ekat

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/Omega#54]
When I try to build Omega on Perlmutter with `nvidia`:
```
export METIS_ROOT=/pscratch/sd/x/xylar/spack_pm-cpu_test//dev_polaris_0_3_0_nvidia_mpich/var/spack/environments/dev_polaris_0_3_0_nvidia_mpich/.spack-env/view
export PARMETIS_ROOT=/pscratch/sd/x/xylar/spack_pm-cpu_test//dev_polaris_0_3_0_nvidia_mpich/var/spack/environments/dev_polaris_0_3_0_nvidia_mpich/.spack-env/view
cmake \
    -DOMEGA_BUILD_TYPE=Release \
    -DOMEGA_CIME_COMPILER=nvidia \
    -DOMEGA_CIME_MACHINE=pm-cpu \
    -DOMEGA_METIS_ROOT=${METIS_ROOT} \
    -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT} \
    -DOMEGA_BUILD_TEST=ON \
    -S /global/u2/x/xylar/e3sm_work/polaris/add-omega-ctest-util/e3sm_submodules/Omega/components/omega/ \
    -B .

./omega_build.sh
```

```
[  7%] Building CXX object external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
nvc++-Error-Unknown switch: -Weffc++
make[2]: *** [external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/build.make:76: external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1109: external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by xylar** [comment]
@grnydawn, I know I'm hitting you with a lot.  This isn't a high priority to fix but I wanted to make sure it's on your radar for if and when you have time.

It's also possible I've made a mistake.

**Comment by grnydawn** [comment]
@xylar , I was able to trace this issue to a GNU-specific compiler flag in 'externals/ekat/extern/yaml-cpp/CMakeLists.txt'. The GNU compiler flag (-Weffc++) caused the error with the PGI compiler (NVHPC). @jgfouca has kindly offered to fix this issue on his side. While we can address this issue by removing the compiler flag from the CMakeLists.txt file, it is outside of the Omega code directory. I suppose we can wait until his fix is merged into E3SM.

**Comment by xylar** [comment]
@grnydawn, yep, that sounds good.  Let's wait for E3SM `master` to have this fix and we'll merge it into Omega `develop` once it does.

**Comment by xylar** [comment]
@grnydawn and @jgfouca, no pressure but just curious if there is any update on this since January.

**Comment by xylar** [comment]
@philipwjones, could we arrange to merge `E3SM/master` into `Omega/develop` at some point to resolve this?
