### ISSUE TITLE
Config ctest failures without reporting

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/Omega#58]
Several Config CTests have failed on Frontier, primarily due to the use of already existing variable names. Some of the error messages include:
```
[2024-02-07 15:09:38.658] [error] [Config.cpp:502] Config add R4: variable HmixR4 already exists use set instead
[2024-02-07 15:09:38.658] [error] [Config.cpp:304] Config set I4: could not find variable junk
[2024-02-07 15:09:38.658] [error] [Config.cpp:139] Config get I4: could not find variable junk
```
This error is not captured by CTest because the error message does not include "FAIL".

This issue is also related to the ongoing discussion about Omega Logging, specifically whether calling LOG_ERROR should cause Omega to exit, though it has not been implemented yet.

**Comment by philipwjones** [comment]
@grnydawn  These errors are intentional - the unit test is testing some failure modes so the error is expected and should not generate a FAIL. But maybe I should change the output so it doesn't cause confusion.

**Comment by grnydawn** [comment]
@philipwjones Oh, I see. Thanks for the info. I think I should close this issue then.
