### ISSUE TITLE
DISCUSSION: CMakeBuild and DataTypes for Kokkos-based OMEGA

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/Omega#67]
This issue is for initiating discussions about the Kokkos-based Omega build and other related topics.

**Approaches for Transitioning to a Kokkos-Based CMake Build and Omega Data Types:**

- Keep the current CMakeBuild user interface as much as possible.
- Retain the current Omega coding practices as much as possible.
- Provide shortcuts for the most-used Kokkos configurations.
- Make it extensible for the incremental introduction of Kokkos features.

The initial attempt at a Kokkos-based CMakeBuild is exemplified in the following link: "https://github.com/grnydawn/Omega/blob/ykim/omega/kokkosbuild-review/components/omega/test/base/DataTypesTest.cpp"

**Key Points:**

1. **Array Creation and Usage:**
   - For usual cases, array creation and usage should remain the same.
     - YAKL-based: `Array1DI4 TstArr1DI4("TstArr1DI4", NumCells);`
     - Kokkos-based: `Array1DI4 TstArr1DI4("TstArr1DI4", NumCells);`

2. **Parallel Loops:**
   - The `parallel_for` structure should be similar.
     - YAKL-based: `parallel_for(Bounds<1>(NumCells), YAKL_LAMBDA(int i) { TstArr1DI4(i) = i; });`
     - Kokkos-based: `parallel_for(DeviceRangePolicy(0, NumCells), KOKKOS_LAMBDA(int i) { TstArr1DI4(i) = i; });`
     - Changes include `YAKL_LAMBDA` to `KOKKOS_LAMBDA` and `Bounds<1>(NumCells)` to `DeviceRangePolicy(0, NumCells)`.
     - Other execution policies like `Device2DRangePolicy`, `Device3DRangePolicy`, etc., are created for convenience.

3. **Data Copy to/from CPU-GPU:**
   - Data transfer between CPU and GPU should be straightforward.
     - YAKL-based: `auto TstHost1DI4 = TstArr1DI4.createHostCopy();`
     - Kokkos-based: `auto TstHost1DI4 = create_mirror_view_and_copy(HostMemSpace(), TstArr1DI4);`
     - Default memory spaces for the host (`HostMemSpace`) and device (`DeviceMemSpace`) are created for convenience.
     - Default memory layouts are also created for convenience.

**Comment by philipwjones** [comment]
@grnydawn  Thanks for starting this. We had some discussions on a call on Monday over some of these topics. I'll address those implications in separate comments for 1,2,3 above. In particular, we thought about doing this incrementally to make it easier to do the conversion (we think Kokkos and YAKL can co-exist for this brief transition - Matt said we should double-check with Jim Foucar).

**Comment by philipwjones** [comment]
For the data arrays (1), I agree that we can retain the same aliases and syntax. If we do an incremental transition, I would propose we first do a blanket name change for YAKL device arrays to YArrayDDKK so that we can use the ArrayDDKK for Kokkos arrays. We can leave the host arrays because I think I want to do a name change anyway, so the Kokkos (final) version would be HstArray or HostArray rather than ArrayHost.

**Comment by philipwjones** [comment]
For the loop syntax (2), I like what you've done, but would prefer a more intuitive name. We could adopt the YAKL Bounds or call it LoopLimits - don't know whether we'd want to use the <NDims> syntax or just do the Bounds1D up to Bounds5D. We might eventually need a host version of this if we need to have OpenMP on the host, but don't anticipate doing much on the host right now so we could keep doing generic for loops on the host for now.

**Comment by grnydawn** [comment]
@philipwjones , thank you for your comments. Based on your feedback, I have some follow-up questions:

1. Regarding the data arrays, do we aim to maintain exactly the same syntax for both Kokkos and YAKL, at least until we need to implement finer controls? Upon reviewing the array syntax for both libraries, I believe it might be feasible to keep them identical by utilizing C++ macros. Alternatively, would we prefer to have similar, yet distinct, array syntaxes?

2. Concerning the loop syntax, do we aim for precisely the same syntax for both Kokkos and YAKL, similar to the previous question, until differentiation becomes necessary for finer controls? I am not yet confident that we can maintain identical syntax for loop constructs. It seems that Kokkos might offer more control options, which we could potentially ignore in YAKL if they are optional and not supported by YAKL.

3. Regarding your third section, I understand the strategies you've outlined. I am only familiar with a limited subset of Kokkos APIs and am uncertain whether we can establish common APIs for most required functions. I will investigate this further.

4. For the gradual transition from YAKL to Kokkos, one potential method to facilitate this change could be to introduce a new CMake macro (such as OMEGA_PORTABILITY_LIBRARY="YAKL OR KOKKOS"). This macro would be used in the source files to dictate which portions of code are compiled, thereby supporting the transition.

**Comment by philipwjones** [comment]
@grnydawn  On 1,2, there's no need to make them exactly the same syntax since we'll be adopting Kokkos fully after the transition. I'm just looking for a simpler vocabulary and syntax for developers - YAKL was a little closer to that (eg I think people understand Bounds rather than RangePolicy) but it doesn't need to be exactly the same as YAKL. And yes, (4) might make things a little easier, especially if Kokkos and YAKL don't interoperate as well as we'd like during the transition.  The transition should be short, so if we have some short-term kludges like that to make it easier and save us some time, that's fine. Thanks.

**Comment by mwarusz** [comment]
One issue that we didn't discuss on Monday, but we need to think about, is array layouts. Kokkos by default uses `LayoutRight` on the host and `LayoutLeft` on device. Is this something that we also want to do in Omega ? Personally, I don't see huge benefits of having different layouts for Omega and I'd vote for sticking with one layout.

Regarding the loop syntax, I have been trying to come up with some wrapper functions that would reduce some of the noise coming from Kokkos. Here is how the current iteration looks for tightly nested loops:
```cpp
    omega_parallel_for(
        "compute_tracer_tendency",
        {ntracers, ncells, nlayers},
        KOKKOS_LAMBDA(Int ltracer, Int icell, Int k) {
    });
   //}, {2, 2, 16}); tile size (optional)
```
Of course, the current name is just a placeholder. In Omega we could use `parallelFor` or `forAll`, for example. I think the main benefit of adding a wrapper like that, in addition to simplyfying syntax,  is that we would have a single place in the code to change default tile sizes. Kokkos defaults may not necessarily work for us.

If you want to see how this wrapper is implemented, it is currently on a branch in my sandbox code:

https://github.com/mwarusz/omega_playground/blob/9807efa385b4f28c8b086079d0603cb0dae24329/src/common.hpp#L71-L83

**Comment by philipwjones** [comment]
@mwarusz  And I like your loop syntax. I personally dislike typing underscores, so my preference would be for a mixed case name, but others can chime in.

**Comment by mwarusz** [comment]
>@mwarusz And I like your loop syntax. I personally dislike typing underscores, so my preference would be for a mixed case name, but others can chime in.

Using Omega naming conventions, I like `parallelFor` the best, since it clearly indicates which Kokkos function it wraps, and it is possible to also add `parallelReduce`, and even `parallelScan` if we're ever going to need it.

**Comment by philipwjones** [comment]
Agreed on name. We need reductions, but they are most often be embedded in a global reduce function that also performs the all-reduce across MPI ranks and performs the sum reductions in a way that is bit-reproducible (easy for most types, but we have an algorithm for R8 that can do this). So we'll have to see what form might work best to manage that.

**Comment by grnydawn** [comment]
@mwarusz, @philipwjones, I agreed on the names 'parallelFor' and 'parallelReduce.' I also like the idea of using wrappers. In addition to the benefit of being a single place for code changes, this approach could also help separate the compilation/linking issues between Kokkos builds and the rest of the Omega build by differentiating the namespaces of the two.

**Comment by grnydawn** [comment]
@mwarusz , @philipwjones , I created a PR (https://github.com/E3SM-Project/Omega/pull/71) in that I tried to apply your comments. Especially, I created "parallelFor" and "parallelReduce" wrappers based on Maciej's base work. I hope you to look at the PR, where "DataTypes.h" and "OmegaKokkos.h" are the main source files for Omega Kokkos transition.

**Comment by grnydawn** [comment]
I am closing this issue since the Kokkos PR (https://github.com/E3SM-Project/Omega/pull/74) has been merged.
