### ISSUE TITLE
Permissions issue in opening file for writing

### ISSUE THREAD

**Issue by sbrus89** [E3SM-Project/Omega#83]
@philipwjones, in the `IO_Test` I'm seeing this error on Frontier when the file is initially opened for writing:

```
PIO: FATAL ERROR: Aborting... FATAL ERROR: Permission denied (file = IOTest.nc) (/ccs/home/brus/project/Omega/externals/scorpio/src/clib/pioc_support.c: 3429)
```

This is showing up in the `LastTest.log` file, but isn't causing the test to show up as failed in the CTest output.

**Comment by philipwjones** [comment]
@sbrus89 Are you running from a scratch space? On Frontier, the tests need to be run on the high-performance scratch filesystems. The compute nodes do not have full access to some of the other filesystems. I think this is documented in our User guide.

**Comment by sbrus89** [comment]
@philipwjones, you're right. Sorry I forgot about that.
